update kopi installer

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,7 +1,7 @@
 #!/sbin/sh
-# Kopi Installer V1.1
+# Kopi Installer V1.8
 # Since 08-05-2020
-# Latest Update 17-03-2021
+# Latest Update 21-01-2022
 # by wahyu6070 (dont change)
 
 OUTFD=/proc/self/fd/$2;
@@ -144,7 +144,251 @@ set_prop() {
     echo "${property}=${value}" >>"${file_location}"
   fi
 }
+
 ########################################
+#   Mount Partipations
+########################################
+setenforce 0
+# osm0sis : https://github.com/osm0sis/AnyKernel3
+[ -d /postinstall/tmp ] && POSTINSTALL=/postinstall;
+[ "$AKHOME" ] || AKHOME=$POSTINSTALL/tmp/anykernel;
+[ "$ANDROID_ROOT" ] || ANDROID_ROOT=/system;
+
+
+file_getprop() {  grep "^$2=" "$1" |  cut -d= -f2-; }
+find_slot() {
+  local slot=$(getprop ro.boot.slot_suffix 2>/dev/null);
+  [ "$slot" ] || slot=$( grep -o 'androidboot.slot_suffix=.*$' /proc/cmdline |  cut -d\  -f1 |  cut -d= -f2);
+  if [ ! "$slot" ]; then
+    slot=$(getprop ro.boot.slot 2>/dev/null);
+    [ "$slot" ] || slot=$( grep -o 'androidboot.slot=.*$' /proc/cmdline |  cut -d\  -f1 |  cut -d= -f2);
+    [ "$slot" ] && slot=_$slot;
+  fi;
+  [ "$slot" ] && echo "$slot";
+}
+setup_mountpoint() {
+  [ -L $1 ] &&  mv -f $1 ${1}_link;
+  if [ ! -d $1 ]; then
+     rm -f $1;
+     mkdir -p $1;
+  fi;
+}
+is_mounted() {  mount |  grep -q " $1 "; }
+mount_apex() {
+  [ -d /system_root/system/apex ] || return 1;
+  local apex dest loop minorx num var;
+  setup_mountpoint /apex;
+   mount -t tmpfs tmpfs /apex -o mode=755 &&  touch /apex/apextmp;
+  minorx=1;
+  [ -e /dev/block/loop1 ] && minorx=$( ls -l /dev/block/loop1 |  awk '{ print $6 }');
+  num=0;
+  for apex in /system_root/system/apex/*; do
+    dest=/apex/$( basename $apex .apex);
+    case $dest in
+      *.current|*.release) dest=$(echo $dest |  rev |  cut -d. -f2- |  rev);;
+    esac;
+     mkdir -p $dest;
+    case $apex in
+      *.apex)
+         unzip -qo $apex apex_payload.img -d /apex;
+         mv -f /apex/apex_payload.img $dest.img;
+         mount -t ext4 -o ro,noatime $dest.img $dest 2>/dev/null;
+        if [ $? != 0 ]; then
+          while [ $num -lt 64 ]; do
+            loop=/dev/block/loop$num;
+            [ -e $loop ] ||  mknod $loop b 7 $((num * minorx));
+             losetup $loop $dest.img 2>/dev/null;
+            num=$((num + 1));
+             losetup $loop |  grep -q $dest.img && break;
+          done;
+           mount -t ext4 -o ro,loop,noatime $loop $dest;
+          if [ $? != 0 ]; then
+             losetup -d $loop 2>/dev/null;
+          fi;
+        fi;
+      ;;
+      *)  mount -o bind $apex $dest;;
+    esac;
+  done;
+  for var in $( grep -o 'export .* /.*' /system_root/init.environ.rc |  awk '{ print $2 }'); do
+    eval OLD_${var}=\$$var;
+  done;
+  $( grep -o 'export .* /.*' /system_root/init.environ.rc |  sed 's; /;=/;'); unset export;
+}
+umount_apex() {
+  [ -d /apex ] || return 1;
+  local dest loop var;
+  for var in $( grep -o 'export .* /.*' /system_root/init.environ.rc 2>/dev/null |  awk '{ print $2 }'); do
+    if [ "$(eval echo \$OLD_$var)" ]; then
+      eval $var=\$OLD_${var};
+    else
+      eval unset $var;
+    fi;
+    unset OLD_${var};
+  done;
+  for dest in $( find /apex -type d -mindepth 1 -maxdepth 1); do
+    loop=$( mount |  grep $dest |  grep loop |  cut -d\  -f1);
+     umount -l $dest;
+    [ "$loop" ] &&  losetup -d $loop;
+  done;
+  [ -f /apex/apextmp ] &&  umount /apex;
+   rm -rf /apex 2>/dev/null;
+}
+mount_all() {
+  local byname mount slot system;
+  if ! is_mounted /cache; then
+     mount /cache 2>/dev/null && UMOUNT_CACHE=1;
+  fi;
+  if ! is_mounted /data; then
+     mount /data && UMOUNT_DATA=1;
+  fi;
+  (for mount in /vendor /product /system_ext /persist; do
+     mount -o ro -t auto $mount;
+  done) 2>/dev/null;
+  setup_mountpoint $ANDROID_ROOT;
+  if ! is_mounted $ANDROID_ROOT; then
+     mount -o ro -t auto $ANDROID_ROOT 2>/dev/null;
+  fi;
+  byname=bootdevice/by-name;
+  [ -d /dev/block/$byname ] || byname=$( find /dev/block/platform -type d -name by-name 2>/dev/null |  head -n1 |  cut -d/ -f4-);
+  [ -d /dev/block/mapper ] && byname=mapper;
+  [ -e /dev/block/$byname/system ] || slot=$(find_slot);
+  case $ANDROID_ROOT in
+    /system_root) setup_mountpoint /system;;
+    /system)
+      if ! is_mounted /system && ! is_mounted /system_root; then
+        setup_mountpoint /system_root;
+         mount -o ro -t auto /system_root;
+      elif [ -f /system/system/build.prop ]; then
+        setup_mountpoint /system_root;
+         mount --move /system /system_root;
+      fi;
+      if [ $? != 0 ]; then
+        ( umount /system;
+         umount -l /system) 2>/dev/null;
+         mount -o ro -t auto /dev/block/$byname/system$slot /system_root;
+      fi;
+    ;;
+  esac;
+  [ -f /system_root/system/build.prop ] && system=/system;
+  for mount in /vendor /product /system_ext; do
+    if ! is_mounted $mount && [ -L /system$mount -o -L /system_root$system$mount ]; then
+      setup_mountpoint $mount;
+       mount -o ro -t auto /dev/block/$byname$mount$slot $mount;
+    fi;
+  done;
+  if is_mounted /system_root; then
+    mount_apex;
+     #mount -o bind /system_root$system /system;
+  fi;
+  if ! is_mounted /persist && [ -e /dev/block/bootdevice/by-name/persist ]; then
+    setup_mountpoint /persist;
+     mount -o ro -t auto /dev/block/bootdevice/by-name/persist /persist;
+  fi;
+  
+  #if [ -d /dev/block/mapper ]; then
+    #for block in system vendor product system_ext; do
+      #for slot in "" _a _b; do
+        #blockdev --setrw /dev/block/mapper/$block$slot 2>/dev/null
+      #done
+    #done
+  #fi
+}
+umount_all() {
+  local mount;
+  (if [ ! -d /postinstall/tmp ]; then
+     umount /system;
+     umount -l /system;
+  fi) 2>/dev/null;
+  umount_apex;
+  (if [ ! -d /postinstall/tmp ]; then
+     umount /system_root;
+     umount -l /system_root;
+  fi;
+  umount /vendor; # busybox umount /vendor breaks recovery on some hacky devices
+  umount -l /vendor;
+  for mount in /mnt/system /mnt/vendor /product /mnt/product /system_ext /mnt/system_ext /persist; do
+     umount $mount;
+     umount -l $mount;
+  done;
+  if [ "$UMOUNT_DATA" ]; then
+     umount /data;
+     umount -l /data;
+  fi;
+  if [ "$UMOUNT_CACHE" ]; then
+     umount /cache;
+     umount -l /cache;
+  fi) 2>/dev/null;
+}
+setup_env() {
+  $BOOTMODE && return 1;
+   mount -o bind /dev/urandom /dev/random;
+  if [ -L /etc ]; then
+    setup_mountpoint /etc;
+     cp -af /etc_link/* /etc;
+     sed -i 's; / ; /system_root ;' /etc/fstab;
+  fi;
+  umount_all;
+  mount_all;
+  OLD_LD_PATH=$LD_LIBRARY_PATH;
+  OLD_LD_PRE=$LD_PRELOAD;
+  OLD_LD_CFG=$LD_CONFIG_FILE;
+  unset LD_LIBRARY_PATH LD_PRELOAD LD_CONFIG_FILE;
+  if [ ! "$(getprop 2>/dev/null)" ]; then
+    getprop() {
+      local propdir propfile propval;
+      for propdir in / /system_root /system /vendor /product /system_ext /odm; do
+        for propfile in default.prop build.prop; do
+          if [ "$propval" ]; then
+            break 2;
+          else
+            propval="$(file_getprop $propdir/$propfile $1 2>/dev/null)";
+          fi;
+        done;
+      done;
+      if [ "$propval" ]; then
+        echo "$propval";
+      else
+        echo "";
+      fi;
+    }
+  elif [ ! "$(getprop ro.build.type 2>/dev/null)" ]; then
+    getprop() {
+      ($(which getprop) |  grep "$1" |  cut -d[ -f3 |  cut -d] -f1) 2>/dev/null;
+    }
+  fi;
+}
+restore_env() {
+  $BOOTMODE && return 1;
+  local dir;
+  unset -f getprop;
+  [ "$OLD_LD_PATH" ] && export LD_LIBRARY_PATH=$OLD_LD_PATH;
+  [ "$OLD_LD_PRE" ] && export LD_PRELOAD=$OLD_LD_PRE;
+  [ "$OLD_LD_CFG" ] && export LD_CONFIG_FILE=$OLD_LD_CFG;
+  unset OLD_LD_PATH OLD_LD_PRE OLD_LD_CFG;
+  umount_all;
+  [ -L /etc_link ] &&  rm -rf /etc/*;
+  (for dir in /etc /apex /system_root /system /vendor /product /system_ext /persist; do
+    if [ -L "${dir}_link" ]; then
+      rmdir $dir;
+       mv -f ${dir}_link $dir;
+    fi;
+  done;
+   umount -l /dev/random) 2>/dev/null;
+}
+  
+if $BOOTMODE; then
+	mount -o rw,remount -t auto / || mount -o rw,remount / 2>/dev/null;
+else
+	setup_env
+	for W78 in /system /product /system_ext /system_root /vendor; do
+		if is_mounted $W78; then
+			mount -o rw,remount -t auto $W78 2>/dev/null || print "! Failed mounting R/W <$W78>"
+		fi
+	done
+fi
+
+#########################################
 #    Kopi Script
 ########################################
 	
@@ -154,53 +398,65 @@ print "- Kopi Installer by wahyu6070";
 print " "
 show_progress 1.34 0;
 
-#mount
-print "- Mounting"
-active_slot=`getprop ro.boot.slot_suffix`
-if [ ! -z "$active_slot" ]; then
-  device_abpartition=true
-  if [ -n "$(cat /etc/fstab | grep /system_root)" ];
-  then
-    MOUNT_POINT=/system_root
-  else
-    MOUNT_POINT=/system
-  fi
-elif [ -n "$(cat /etc/fstab | grep /system_root)" ];
-then
-  device_abpartition=false
-  MOUNT_POINT=/system_root
-else
-  device_abpartition=false
-  MOUNT_POINT=/system
-fi
-mount -o rw,remount $MOUNT_POINT || mount $MOUNT_POINT || mount -o rw,remount -t auto $MOUNT_POINT || mount -o rw,remount / || abort "- Abort mounting system"
-mount -o rw,remount /vendor || mount /vendor || mount -o rw,remount -t auto /vendor || mount -o rw,remount / || abort "- Abort mounting vendor"
-test -f /system/system/build.prop && root=/system/system;
-set_progress 0.4;
-
 #system dir
 if [ -f /system/system/build.prop ]; then
-system=/system/system
+	SYSTEM=/system/system
 elif [ -f /system_root/system/build.prop ]; then
-system=/system_root/system
+	SYSTEM=/system_root/system
 elif [ -f /system_root/build.prop ]; then
-system=/system_root
+	SYSTEM=/system_root
 else
-system=/system
+	SYSTEM=/system
+fi
+
+#vendor dir
+VENDOR=/vendor
+
+# /product dir (android 10+)
+if [ ! -L $SYSTEM/product ]; then
+	PRODUCT=$SYSTEM/product
+else
+	PRODUCT=/product
+fi
+
+# /system_ext dir (android 11+)
+if [ ! -L $SYSTEM/system_ext ]; then
+	SYSTEM_EXT=$SYSTEM/system_ext
+else
+	SYSTEM_EXT=/system_ext
 fi
 
 #Extract
-kopi=/dev/tmp/kopi
-MODPATH=$kopi
-TMPDIR=/dev/tmp
-cdir $kopi;
+cdir /data/kopi_test
+touch /data/kopi_test/kopi_test_file
+if [ $? -eq 0 ]; then
+	del /data/kopi_test/kopi_test_file
+	del /data/kopi_test
+	export TMPDIR=/data/tmp
+else
+	export TMPDIR=/dev/tmp
+fi
+
+#variable
+TMPDIR6070=$TMPDIR
+export kopi=$TMPDIR/kopi
+export MODPATH=$kopi
+
+if [ -d $kopi ]; then
+	del $kopi
+	cdir $kopi || abort "- failed make dir $kopi"
+else
+	cdir $kopi || abort "- failed make dir $kopi"
+fi
+
 cd $kopi
 print "- Extracting ZIP File"
 unzip -o "$ZIPFILE" >&2
+
 [ ! -f module.prop ] && abort "- Module.prop Not Found"
 
 #prop
-prop=$system/build.prop
+prop=$SYSTEM/build.prop
 API=`getp ro.build.version.sdk $prop`
 ABI=`getp ro.product.cpu.abi $prop | cut -c-3`
 ABI2=`getp ro.product.cpu.abi2 $prop | cut -c-3`
@@ -213,16 +469,17 @@ if [ "$ABI2" = "x86" ]; then ARCH=x86; ARCH32=x86; fi;
 if [ "$ABILONG" = "arm64-v8a" ]; then ARCH=arm64; ARCH32=arm; IS64BIT=true; fi;
 if [ "$ABILONG" = "x86_64" ]; then ARCH=x64; ARCH32=x86; IS64BIT=true; fi;
 
-MODULE=./module.prop
-ID=`getp id $MODULE`
-NAME=`getp name $MODULE`
-VERSION=`getp version $MODULE`
-VERSIONCODE=`getp versioncode $MODULE`
-DEVICE=`getp device $MODULE`
-DATE=`getp date $MODULE`
-AUTHOR=`getp author $MODULE`
-KOPIMOD=/data/kopi/modules/"$ID"
-MAGISKMOD=/data/adb/modules/$ID
+export MODULE=./module.prop
+export ID=`getp id $MODULE`
+export NAME=`getp name $MODULE`
+export VERSION=`getp version $MODULE`
+export VERSIONCODE=`getp versioncode $MODULE`
+export DEVICE=`getp device $MODULE`
+export DATE=`getp date $MODULE`
+export AUTHOR=`getp author $MODULE`
+export KOPIMOD=/data/kopi/modules/"$ID"
+export MAGISKMOD=/data/adb/modules/$ID
+export MAGISKUP="/data/adb/modules_update/$ID"
 set_progress 0.5;
 
 #req
@@ -233,20 +490,34 @@ fi
 
 #Type install
 if [ $(getp typeinstall $MODULE) = kopi ]; then TYPEINSTALL=kopi
+elif [ -f /sdcard/force_kopi ]; then TYPEINSTALL=kopi
+elif [ -f /dev/force_kopi ]; then TYPEINSTALL=kopi
 elif [ $(getp typeinstall $MODULE) = magisk ]; then TYPEINSTALL=magisk
 elif [ $(getp typeinstall $MODULE) = false ]; then TYPEINSTALL=false
 else
-$BOOTMODE && TYPEINSTALL=magisk || [ -f /data/adb/magisk/magisk ] && TYPEINSTALL=magisk || TYPEINSTALL=kopi
+	if $BOOTMODE; then
+		TYPEINSTALL=magisk
+	elif [ -f /data/adb/magisk/util_functions.sh ]; then
+		TYPEINSTALL=magisk
+	else
+		TYPEINSTALL=kopi
+	fi
 fi
 
 # Uninstall
 if [ -f $KOPIMOD/uninstall.sh ] && [ $(cat $KOPIMOD/typeinstall) = kopi ] && [ $(getp versioncode $KOPIMOD/module.prop) -eq $VERSIONCODE ]; then
 	print "- Uninstalling $NAME"
-	test -f $KOPIMOD/uninstall.sh && . $KOPIMOD/uninstall.sh || abort "- Uninstalling failed !"
+	test -f $KOPIMOD/uninstall.sh && . $KOPIMOD/uninstall.sh
 	del $KOPIMOD
 	uninstallmode=true
 else
 # Installing
+	if [ -d $KOPIMOD ]; then
+		del $KOPIMOD
+		cdir $KOPIMOD
+	else
+		cdir $KOPIMOD
+	fi
 	cdir $KOPIMOD
 	[ -f uninstall.sh ] && cp -pf uninstall.sh $KOPIMOD && chmod 775 $KOPIMOD/uninstall.sh;
 	echo "$TYPEINSTALL" > $KOPIMOD/typeinstall
@@ -259,58 +530,88 @@ else
 	magisk)
 	print "- Type Magisk Module"
 	[ -f /data/adb/magisk/util_functions.sh ] && [ $TYPEINSTALL = magisk ] && . /data/adb/magisk/util_functions.sh
-	modup="/data/adb/modules_update/$ID"
-	del $modup
-	cdir "$modup"
-	cdir "/data/adb/modules/$ID"
+	for W8989 in $MAGISKMOD $MAGISKUP; do
+		test -d $W8989 && del $W8989 && cdir $W8989 || cdir $W8989
+	done
 	touch "/data/adb/modules/$ID/update"
 	cp -pf $kopi/module.prop "/data/adb/modules/$ID/"
-	[ -f $kopi/magisk-uninstall.sh ] && cp -pf $kopi/magisk-uninstall.sh $modup/uninstall.sh && chmod 755 $modup/uninstall.sh
-	[ -f $kopi/magisk-system.prop ] && cp -pf $kopi/magisk-system.prop $modup/system.prop
-	[ -f $kopi/magisk-service.sh ] && cp -pf $kopi/magisk-service.sh $modup/service.sh && chmod 755 $modup/service.sh
-	[ -f $kopi/magisk-post-fs-data.sh ] && cp -pf $kopi/magisk-post-fs-data.sh $modup/post-fs-data.sh && chmod 755 $modup/post-fs-data.sh
-	cp -rdf $kopi/* "$modup"
-	del $modup/META-INF
-	del $modup/install.sh
-	del $modup/customize.sh
-	del $modup/install.zip
-	del $modup/README.md
+	if [ -f $kopi/magisk-uninstall.sh ]; then
+		test -f $kopi/uninstall.sh && del $kopi/uninstall.sh
+		cp -pf $kopi/magisk-uninstall.sh $MAGISKUP/uninstall.sh
+		chmod 755 $MAGISKUP/uninstall.sh
+		del $kopi/magisk-uninstall.sh
+	fi
+	if [ -f $kopi/magisk-system.prop ]; then
+		cp -pf $kopi/magisk-system.prop $MAGISKUP/system.prop
+		del $kopi/magisk-system.prop
+	fi
+	if [ -f $kopi/magisk-service.sh ]; then
+		cp -pf $kopi/magisk-service.sh $MAGISKUP/service.sh
+		chmod 755 $MAGISKUP/service.sh
+		del $kopi/magisk-service.sh
+	fi
+	if [ -f $kopi/magisk-post-fs-data.sh ]; then
+		cp -pf $kopi/magisk-post-fs-data.sh $MAGISKUP/post-fs-data.sh
+		chmod 755 $MAGISKUP/post-fs-data.sh
+		del $kopi/magisk-post-fs-data.sh
+	fi
+	cp -rdf $kopi/* "$MAGISKUP"
+	
+	LIST_RM="
+	$MAGISKUP/META-INF
+	$MAGISKUP/install.sh
+	$MAGISKUP/customize.sh
+	$MAGISKUP/install.zip
+	$MAGISKUP/README.md
+	"
+	for W7878 in $LIST_RM; do
+		del $W7878
+	done
 	;;
 	kopi)
 	print "- Type Kopi Module"
+	
+	for MV_DIR in vendor product system_ext; do
+		if [ -d $kopi/system/$MV_DIR ] && [ "$(ls -A $kopi/system/$MV_DIR)" ]; then
+			test ! -d $kopi/$MV_DIR && cdir $kopi/$MV_DIR
+			cp -rdf $kopi/system/$MV_DIR/* $kopi/$MV_DIR/
+			del del $kopi/system/$MV_DIR
+		elif [ -d $kopi/system/$MV_DIR ] && [ ! "$(ls -A $kopi/system/$MV_DIR)" ]; then
+			del $kopi/system/$MV_DIR
+		fi
+	done
+	
 	#Creating list file or dir installed log
-	if [ -d $MODPATH/system ] && [ "$(ls -A $MODPATH/system)" ]; then
-		cd $MODPATH/system
-		for make_perm_sys in $(find *); do
-			echo "$make_perm_sys" >> $KOPIMOD/list_install_system
-		done
-	fi
-
-	if [ -d $MODPATH/vendor ] && [ "$(ls -A $MODPATH/vendor)" ]; then
-		cd $MODPATH/vendor
-		for make_perm_ven in $(find *); do
-			echo "$make_perm_ven" >> $KOPIMOD/list_install_vendor
-		done
-	fi
+	for MAKE_LIST in system vendor product system_ext; do
+		if [ -d $MODPATH/$MAKE_LIST ] && [ "$(ls -A $MODPATH/$MAKE_LIST)" ]; then
+			cd $MODPATH/$MAKE_LIST
+			for MAKE_LIST_FILE in $(find *); do
+				echo "$MAKE_LIST_FILE" >> $KOPIMOD/list_install_$MAKE_LIST
+			done
+		fi
+	done
 	
-	#cp /system/vendor
-	if [ -d $kopi/system/vendor ] && [ "$(ls -A $kopi/system/vendor)" ]; then
-		cdir $kopi/vendor
-		cp -rdf $kopi/system/vendor/* $kopi/vendor/;
-		del $kopi/system/vendor
-	elif [ -d $kopi/system/vendor ] && [ ! "$(ls -A $kopi/system/vendor)" ]; then
-		del $kopi/system/vendor
-	fi;
-	
-	#cp /system
-	if [ -d $kopi/system ] && [ "$(ls -A $kopi/system)" ]; then
+	#cp system
+	if [ -d $kopi/system ] && ! rmdir $kopi/system 2>/dev/null; then
 		print "- Pushing system";
-		cp -rdf $kopi/system/* $system/;
+		cp -rdf $kopi/system/* $SYSTEM/;
 	fi;
 	#cp vendor
-	if [ -d $kopi/vendor ] && [ "$(ls -A $kopi/vendor)" ]; then
-		print "- Pushing vendor"; 
-		cp -rdf $kopi/vendor/* /vendor/;
+	if [ -d $kopi/vendor ] && ! rmdir $kopi/vendor 2>/dev/null; then
+		print "- Pushing vendor";
+		cp -rdf $kopi/vendor/* $VENDOR/;
+	fi;
+	
+	#cp product
+	if [ -d $kopi/product ] && ! rmdir $kopi/product 2>/dev/null; then
+		print "- Pushing product";
+		cp -rdf $kopi/product/* $PRODUCT/;
+	fi;
+	
+	#cp system_ext
+	if [ -d $kopi/system_ext ] && ! rmdir $kopi/system_ext 2>/dev/null; then
+		print "- Pushing system_ext";
+		cp -rdf $kopi/system_ext/* $SYSTEM_EXT/;
 	fi;
 	set_progress 8.1;
 	;;
@@ -325,19 +626,18 @@ fi
 #permissions
 if [ -f $kopi/permissions.sh ] && [ ! $uninstallmode ]; then
 print "- Set Permissions"
-chmod 775 $kopi/permissions.sh
+chmod 755 $kopi/permissions.sh
 . $kopi/permissions.sh
 fi
 
 #umount
-print "- Umounting";
-if [ $TYPEINSTALL = kopi ]; then
-umount /system
-umount /vendor
+print "- Umounting partitions";
+if ! $BOOTMODE; then
+	restore_env
 fi
 set_progress 1.1;
 cd /;
-del $TMPDIR
+del $TMPDIR6070
 print "- Done";
 set_progress 0.3;
 exit 0;
