Using kopi installer script

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,173 +1,343 @@
 #!/sbin/sh
+# Kopi Installer V1.1
+# Since 08-05-2020
+# Latest Update 17-03-2021
+# by wahyu6070 (dont change)
 
-#################
-# Initialization
-#################
+OUTFD=/proc/self/fd/$2;
+ZIPFILE="$3";
 
-umask 022
+ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true || BOOTMODE=false;
+$BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true;
+$BOOTMODE && OUTFD=/proc/self/fd/0;
+########################################
+# Util Functions
+########################################
 
-# Global vars
-TMPDIR=/dev/tmp
-PERSISTDIR=/sbin/.magisk/mirror/persist
+ui_print() { $BOOTMODE && echo "$1" || echo -e "ui_print $1\nui_print" >> $OUTFD; }
+show_progress() { echo "progress $1 $2" > $OUTFD; }
+set_progress() { echo "set_progress $1" > $OUTFD; }
 
-rm -rf $TMPDIR 2>/dev/null
-mkdir -p $TMPDIR
+#Kopi functions
+print(){ $BOOTMODE && echo "$1" || echo -e "ui_print $1\nui_print" >> $OUTFD; }
+getp(){ grep "^$1" "$2" | head -n1 | cut -d = -f 2; }
+del(){ rm -rf "$@"; }
+delete(){ rm -rf "$@"; }
+cdir(){ mkdir -p "$@"; }
+abort(){ print "$1"; exit 1; }
 
-# echo before loading util_functions
-ui_print() { echo "$1"; }
+#
+printlog(){
+	print "$1"
+	if [ "$1" != " " ]; then
+	echo "$1 [$(date '+%d/%m/%Y %H:%M:%S')]" >> $log
+	echo "$1 [$(date '+%d/%m/%Y %H:%M:%S')]" >> $loglive
+	else
+	print "$1" >> $log
+	echo "$1" >> $loglive
+	fi
+	}
+sedlog(){
+	echo "[Processing]  $1 [$(date '+%d/%m/%Y %H:%M:%S')]" >> $log
+	echo "[Processing]  $1 [$(date '+%d/%m/%Y %H:%M:%S')]" >> $loglive
+	}
+#
+while_log(){
+	echo "$1" | tee -a $log
+	}
+listlog(){
+	echo " " >> $log
+	echo "---------- Folder List : $1 ----------" >> $log
+	echo " " >> $loglive
+	echo "---------- Folder List : $1 ----------" >> $loglive
+	find "$1" -type f | while read lol; do
+	while_log "| $(du -sah $lol | cut -f 1) | $lol"
+	done >> $loglive
+	echo "--------------------------------------" >> $log
+	echo " " >> $log
+	echo "--------------------------------------" >> $loglive
+	echo " " >> $loglive
+	}
 
-require_new_magisk() {
-  ui_print "*******************************"
-  ui_print " Please install Magisk v19.0+! "
-  ui_print "*******************************"
-  exit 1
+loadings() {
+  PID=$!
+  a=0;
+  while [ -d /proc/$PID ]; do
+    b=$((+1))
+    a=$((a+1))
+    sleep 0.9s
+    printf "\r${@} [${a}Second]"
+  done
 }
 
-is_legacy_script() {
-  unzip -l "$ZIPFILE" install.sh | grep -q install.sh
-  return $?
+loadingm() {
+  PID=$!
+  a=0
+  while [ -d /proc/$PID ]; do
+    b=$((a+1))
+    a=$((h+1))
+    sleep 59.9s
+    printf "\r${@} [${b}Minutes]"
+  done
 }
 
-print_modname() {
-  local len
-  len=`echo -n $MODNAME | wc -c`
-  len=$((len + 2))
-  local pounds=`printf "%${len}s" | tr ' ' '*'`
-  ui_print "$pounds"
-  ui_print " $MODNAME "
-  ui_print "$pounds"
-  ui_print "*******************"
-  ui_print " Powered by Magisk "
-  ui_print "*******************"
+loadingz() {
+  PID=$!
+  a=0
+  while [ -d /proc/$PID ]; do
+    b=$((a+1))
+    a=$((a+1))
+    sleep 0.9s
+    printf "#"
+  done
 }
 
-##############
-# Environment
-##############
+printmid() {
+  local CHAR=$(printf "$@" | sed 's|\\e[[0-9;]*m||g' | wc -m)
+  local hfCOLUMN=$((COLUMNS/2))
+  local hfCHAR=$((CHAR/2))
+  local indent=$((hfCOLUMN-hfCHAR))
+  echo "$(printf '%*s' "${indent}" '') $@"
+}
 
-OUTFD=$2
-ZIPFILE=$3
+setime(){
+	if [[ $1 == '-f' ]] && [ "$2" ] && [ $3 -eq $3 ]; then
+	   if [ -f "$2" ]; then
+	      touch -ct $3 "$2" 2>/dev/null || echo "setime: bad '$3': Value too large for defined data type"
+	   else
+	      echo "setime: $2: Is not file"
+	   fi
+	elif [[ $1 == '-r' ]] && [ "$2" ] && [ $3 -eq $3 ]; then
+	   if [ -d "$2" ]; then
+	      find "$2" -print | while read filename; do
+	      touch -ct $3 "$filename" 2>/dev/null || echo "setime: bad '$3': Value too large for defined data type"
+	      done
+	   else
+	      echo "setime: $2: Is not directory"
+	   fi
+	elif [[ $1 == '--version' ]] || [[ $1 == '-v' ]]; then
+	echo "setime v1.0 Copyright (C) 2020 wahyu kurniawan (wahyu6070)."
+    elif [[ $1 == '--help' ]] || [[ $1 == '-h' ]]; then
+    echo "usage : setime <options> <input> <datetime>"
+    echo " "
+    echo "example : setime -r /sdcard/download 202004081503"
+    echo " "
+    echo "options"
+    echo "-f                    file"
+    echo "-r                    change all directory and file"
+    echo "-v, --version         version"
+    echo "-h, --help            help"
+    echo " "
+    echo "setime v1.0 since 2020-04-09 Copyright (C) 2020 wahyu kurniawan (wahyu6070)."
+    else
+    echo "usage : setime --help"
+    fi
+}
 
-mount /data 2>/dev/null
-
-# Load utility functions
-[ -f /data/adb/magisk/util_functions.sh ] || require_new_magisk
-. /data/adb/magisk/util_functions.sh
-[ $MAGISK_VER_CODE -gt 18100 ] || require_new_magisk
-
-# Preperation for flashable zips
-setup_flashable
-
-# Mount partitions
-mount_partitions
-
-# Detect version and architecture
-api_level_arch_detect
-
-# Setup busybox and binaries
-$BOOTMODE && boot_actions || recovery_actions
-
-##############
-# Preparation
-##############
-
-# Extract prop file
-unzip -o "$ZIPFILE" module.prop -d $TMPDIR >&2
-[ ! -f $TMPDIR/module.prop ] && abort "! Unable to extract zip file!"
-
-$BOOTMODE && MODDIRNAME=modules_update || MODDIRNAME=modules
-MODULEROOT=$NVBASE/$MODDIRNAME
-MODID=`grep_prop id $TMPDIR/module.prop`
-MODPATH=$MODULEROOT/$MODID
-MODNAME=`grep_prop name $TMPDIR/module.prop`
-
-# Create mod paths
-rm -rf $MODPATH 2>/dev/null
-mkdir -p $MODPATH
-
-##########
-# Install
-##########
-
-if is_legacy_script; then
-  unzip -oj "$ZIPFILE" module.prop install.sh uninstall.sh 'common/*' -d $TMPDIR >&2
-
-  # Load install script
-  . $TMPDIR/install.sh
-
-  # Callbacks
-  print_modname
-  on_install
-
-  # Custom uninstaller
-  [ -f $TMPDIR/uninstall.sh ] && cp -af $TMPDIR/uninstall.sh $MODPATH/uninstall.sh
-
-  # Skip mount
-  $SKIPMOUNT && touch $MODPATH/skip_mount
-
-  # prop file
-  $PROPFILE && cp -af $TMPDIR/system.prop $MODPATH/system.prop
-
-  # Module info
-  cp -af $TMPDIR/module.prop $MODPATH/module.prop
-
-  # post-fs-data scripts
-  $POSTFSDATA && cp -af $TMPDIR/post-fs-data.sh $MODPATH/post-fs-data.sh
-
-  # service scripts
-  $LATESTARTSERVICE && cp -af $TMPDIR/service.sh $MODPATH/service.sh
-
-  ui_print "- Setting permissions"
-  set_permissions
-else
-  print_modname
-
-  unzip -o "$ZIPFILE" customize.sh -d $MODPATH >&2
-
-  if ! grep -q '^SKIPUNZIP=1$' $MODPATH/customize.sh 2>/dev/null; then
-    ui_print "- Extracting module files"
-    unzip -o "$ZIPFILE" -x 'META-INF/*' -d $MODPATH >&2
-
-    # Default permissions
-    set_perm_recursive $MODPATH 0 0 0755 0644
+set_prop() {
+  property="$1"
+  value="$2"
+  file_location="$3"
+  if grep -q "${property}" "${file_location}"; then
+    sed -i "s/\(${property}\)=.*/\1=${value}/g" "${file_location}"
+  else
+    echo "${property}=${value}" >>"${file_location}"
   fi
+}
+########################################
+#    Kopi Script
+########################################
+	
+#(dont change)
+print " ";
+print "- Kopi Installer by wahyu6070";
+print " "
+show_progress 1.34 0;
 
-  # Load customization script
-  [ -f $MODPATH/customize.sh ] && . $MODPATH/customize.sh
+#mount
+print "- Mounting"
+active_slot=`getprop ro.boot.slot_suffix`
+if [ ! -z "$active_slot" ]; then
+  device_abpartition=true
+  if [ -n "$(cat /etc/fstab | grep /system_root)" ];
+  then
+    MOUNT_POINT=/system_root
+  else
+    MOUNT_POINT=/system
+  fi
+elif [ -n "$(cat /etc/fstab | grep /system_root)" ];
+then
+  device_abpartition=false
+  MOUNT_POINT=/system_root
+else
+  device_abpartition=false
+  MOUNT_POINT=/system
+fi
+mount -o rw,remount $MOUNT_POINT || mount $MOUNT_POINT || mount -o rw,remount -t auto $MOUNT_POINT || mount -o rw,remount / || abort "- Abort mounting system"
+mount -o rw,remount /vendor || mount /vendor || mount -o rw,remount -t auto /vendor || mount -o rw,remount / || abort "- Abort mounting vendor"
+test -f /system/system/build.prop && root=/system/system;
+set_progress 0.4;
+
+#system dir
+if [ -f /system/system/build.prop ]; then
+system=/system/system
+elif [ -f /system_root/system/build.prop ]; then
+system=/system_root/system
+elif [ -f /system_root/build.prop ]; then
+system=/system_root
+else
+system=/system
 fi
 
-# Handle replace folders
-for TARGET in $REPLACE; do
-  ui_print "- Replace target: $TARGET"
-  mktouch $MODPATH$TARGET/.replace
-done
+#Extract
+kopi=/dev/tmp/kopi
+MODPATH=$kopi
+TMPDIR=/dev/tmp
+cdir $kopi;
+cd $kopi
+print "- Extracting ZIP File"
+unzip -o "$ZIPFILE" >&2
+[ ! -f module.prop ] && abort "- Module.prop Not Found"
 
-if $BOOTMODE; then
-  # Update info for Magisk Manager
-  mktouch $NVBASE/modules/$MODID/update
-  cp -af $MODPATH/module.prop $NVBASE/modules/$MODID/module.prop
+#prop
+prop=$system/build.prop
+API=`getp ro.build.version.sdk $prop`
+ABI=`getp ro.product.cpu.abi $prop | cut -c-3`
+ABI2=`getp ro.product.cpu.abi2 $prop | cut -c-3`
+ABILONG=`getp ro.product.cpu.abi $prop`
+ARCH=arm
+ARCH32=arm
+IS64BIT=false
+if [ "$ABI" = "x86" ]; then ARCH=x86; ARCH32=x86; fi;
+if [ "$ABI2" = "x86" ]; then ARCH=x86; ARCH32=x86; fi;
+if [ "$ABILONG" = "arm64-v8a" ]; then ARCH=arm64; ARCH32=arm; IS64BIT=true; fi;
+if [ "$ABILONG" = "x86_64" ]; then ARCH=x64; ARCH32=x86; IS64BIT=true; fi;
+
+MODULE=./module.prop
+ID=`getp id $MODULE`
+NAME=`getp name $MODULE`
+VERSION=`getp version $MODULE`
+VERSIONCODE=`getp versioncode $MODULE`
+DEVICE=`getp device $MODULE`
+DATE=`getp date $MODULE`
+AUTHOR=`getp author $MODULE`
+KOPIMOD=/data/kopi/modules/"$ID"
+MAGISKMOD=/data/adb/modules/$ID
+set_progress 0.5;
+
+#req
+minsdk=`getp minsdk $MODULE`
+if [ $minsdk -eq $minsdk ] && [ $API -lt $minsdk ]; then
+abort "- Android version not support !"
 fi
 
-# Copy over custom sepolicy rules
-if [ -f $MODPATH/sepolicy.rule -a -e $PERSISTDIR ]; then
-  ui_print "- Installing custom sepolicy patch"
-  PERSISTMOD=$PERSISTDIR/magisk/$MODID
-  mkdir -p $PERSISTMOD
-  cp -af $MODPATH/sepolicy.rule $PERSISTMOD/sepolicy.rule
+#Type install
+if [ $(getp typeinstall $MODULE) = kopi ]; then TYPEINSTALL=kopi
+elif [ $(getp typeinstall $MODULE) = magisk ]; then TYPEINSTALL=magisk
+elif [ $(getp typeinstall $MODULE) = false ]; then TYPEINSTALL=false
+else
+$BOOTMODE && TYPEINSTALL=magisk || [ -f /data/adb/magisk/magisk ] && TYPEINSTALL=magisk || TYPEINSTALL=kopi
 fi
 
-# Remove stuffs that don't belong to modules
-rm -rf \
-$MODPATH/system/placeholder $MODPATH/customize.sh \
-$MODPATH/README.md $MODPATH/.git* 2>/dev/null
+# Uninstall
+if [ -f $KOPIMOD/uninstall.sh ] && [ $(cat $KOPIMOD/typeinstall) = kopi ] && [ $(getp versioncode $KOPIMOD/module.prop) -eq $VERSIONCODE ]; then
+	print "- Uninstalling $NAME"
+	test -f $KOPIMOD/uninstall.sh && . $KOPIMOD/uninstall.sh || abort "- Uninstalling failed !"
+	del $KOPIMOD
+	uninstallmode=true
+else
+# Installing
+	cdir $KOPIMOD
+	[ -f uninstall.sh ] && cp -pf uninstall.sh $KOPIMOD && chmod 775 $KOPIMOD/uninstall.sh;
+	echo "$TYPEINSTALL" > $KOPIMOD/typeinstall
+	[ -f module.prop ] && cp -pf module.prop $KOPIMOD;
+	[ -d bin ] && chmod -R 775 $MODPATH/bin;
+	[ -f install.sh ] && chmod 775 install.sh && . ./install.sh;
+	[ -f customize.sh ] && chmod 0775 customize.sh && . ./customize.sh;
+	
+	case $TYPEINSTALL in
+	magisk)
+	print "- Type Magisk Module"
+	[ -f /data/adb/magisk/util_functions.sh ] && [ $TYPEINSTALL = magisk ] && . /data/adb/magisk/util_functions.sh
+	modup="/data/adb/modules_update/$ID"
+	del $modup
+	cdir "$modup"
+	cdir "/data/adb/modules/$ID"
+	touch "/data/adb/modules/$ID/update"
+	cp -pf $kopi/module.prop "/data/adb/modules/$ID/"
+	[ -f $kopi/magisk-uninstall.sh ] && cp -pf $kopi/magisk-uninstall.sh $modup/uninstall.sh && chmod 755 $modup/uninstall.sh
+	[ -f $kopi/magisk-system.prop ] && cp -pf $kopi/magisk-system.prop $modup/system.prop
+	[ -f $kopi/magisk-service.sh ] && cp -pf $kopi/magisk-service.sh $modup/service.sh && chmod 755 $modup/service.sh
+	[ -f $kopi/magisk-post-fs-data.sh ] && cp -pf $kopi/magisk-post-fs-data.sh $modup/post-fs-data.sh && chmod 755 $modup/post-fs-data.sh
+	cp -rdf $kopi/* "$modup"
+	del $modup/META-INF
+	del $modup/install.sh
+	del $modup/customize.sh
+	del $modup/install.zip
+	del $modup/README.md
+	;;
+	kopi)
+	print "- Type Kopi Module"
+	#Creating list file or dir installed log
+	if [ -d $MODPATH/system ] && [ "$(ls -A $MODPATH/system)" ]; then
+		cd $MODPATH/system
+		for make_perm_sys in $(find *); do
+			echo "$make_perm_sys" >> $KOPIMOD/list_install_system
+		done
+	fi
 
-##############
-# Finalizing
-##############
+	if [ -d $MODPATH/vendor ] && [ "$(ls -A $MODPATH/vendor)" ]; then
+		cd $MODPATH/vendor
+		for make_perm_ven in $(find *); do
+			echo "$make_perm_ven" >> $KOPIMOD/list_install_vendor
+		done
+	fi
+	
+	#cp /system/vendor
+	if [ -d $kopi/system/vendor ] && [ "$(ls -A $kopi/system/vendor)" ]; then
+		cdir $kopi/vendor
+		cp -rdf $kopi/system/vendor/* $kopi/vendor/;
+		del $kopi/system/vendor
+	elif [ -d $kopi/system/vendor ] && [ ! "$(ls -A $kopi/system/vendor)" ]; then
+		del $kopi/system/vendor
+	fi;
+	
+	#cp /system
+	if [ -d $kopi/system ] && [ "$(ls -A $kopi/system)" ]; then
+		print "- Pushing system";
+		cp -rdf $kopi/system/* $system/;
+	fi;
+	#cp vendor
+	if [ -d $kopi/vendor ] && [ "$(ls -A $kopi/vendor)" ]; then
+		print "- Pushing vendor"; 
+		cp -rdf $kopi/vendor/* /vendor/;
+	fi;
+	set_progress 8.1;
+	;;
+	false)
+		print "- Type install manual" ;;
+	*)
+		abort "- Type Install $TYPEINSTALL Not found"
+	;;
+	esac
+fi
 
-cd /
-$BOOTMODE || recovery_cleanup
-rm -rf $TMPDIR
+#permissions
+if [ -f $kopi/permissions.sh ] && [ ! $uninstallmode ]; then
+print "- Set Permissions"
+chmod 775 $kopi/permissions.sh
+. $kopi/permissions.sh
+fi
 
-ui_print "- Done"
-exit 0
+#umount
+print "- Umounting";
+if [ $TYPEINSTALL = kopi ]; then
+umount /system
+umount /vendor
+fi
+set_progress 1.1;
+cd /;
+del $TMPDIR
+print "- Done";
+set_progress 0.3;
+exit 0;
